name = "event-reservation-app"
pages_build_output_dir = "public"
compatibility_date = "2026-06-04"

# Po wykonaniu:
# npx wrangler d1 create mojebilety-db
# Cloudflare pokaże database_id. Wklej go niżej.
[[d1_databases]]
binding = "DB"
database_name = "mojebilety-db"
database_id = "32040221-75de-4786-b945-c000915523c0"

[vars]
ADMIN_TOKEN = "demo-admin-token"
